title: MobilePay Marketplace
base_url: https://mobilepaydev.github.io/MobilePay-Marketplace/
description: MobilePay Marketplace Seller API documentation.
show_downloads: false
theme: jekyll-theme-minimal
repository: MobilePayDev/MobilePay-Marketplace
